# DESCRIPTION: 	
# Builds, tests, and packages the solution for the main branch.	

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger: none

resources:
  repositories:
  - repository: azure-health-data-services-sdk-build-tools
    type: git
    name: AzureHealthDataServicesSdk/azure-health-data-services-sdk-build-tools

variables:
  - group: sdk-test-pack
  - group: sdk-build-version-configuration

  - name: packageversion-prerelease-no-suffix
    value: $(ahds-sdk-prerelease-major).$(ahds-sdk-prerelease-minor).$(ahds-sdk-prerelease-patch)
  - name: packageversion-prerelease
    value: $(packageversion-prerelease-no-suffix)-prerelease
  - name: packageversion-release
    value: $(ahds-sdk-release-major).$(ahds-sdk-release-minor).$(ahds-sdk-release-patch)

stages:
  - stage: Build

    jobs:
    - job: CodeChecks
      pool:
        vmImage: $(VmImage)
      steps:
      - template: ./jobs/checkCode.yml

    - job: BuildTestPack
      pool:
        vmImage: $(VmImage)
      steps:
      - template: ./jobs/build.yml
      - template: ./jobs/pack.yml
        parameters:
          ArtifactName: ReleasePackages
          Version: $(packageversion-release)
          AssemblyVersion: $(packageversion-release).$(Build.BuildId)
      - ${{if and(in(variables['Build.Reason'], 'Manual', ''), eq(variables['System.TeamProject'], 'AzureHealthDataServicesSdk'))}}:
        - template: ./jobs/pack.yml
          parameters:
            ArtifactName: PrereleasePackages
            Version: $(packageversion-prerelease)
            AssemblyVersion: $(packageversion-prerelease-no-suffix).$(Build.BuildId)

    # Run release only on manual build (Build.Reason is sometimes blank here) against the internal project. Run for both release and pre-release
  - ${{if and(in(variables['Build.Reason'], 'Manual', ''), eq(variables['System.TeamProject'], 'AzureHealthDataServicesSdk'))}}:
    - template: ./stages/release.yml
      parameters:
        ArtifactName: PrereleasePackages
        PackageVersion: $(packageversion-prerelease)
        DevOpsFeedID: AzureHealthDataServicesSdk/AzureHealthDataServicesSdkInternal
        IsPrerelease: true

    - template: ./stages/release.yml
      parameters:
        ArtifactName: ReleasePackages
        PackageVersion: $(packageversion-release)
        DevOpsFeedID: AzureHealthDataServicesSdk/AzureHealthDataServicesSdkInternal
        IsPrerelease: false